CREATE SCHEMA gold;

CREATE TABLE gold.dim_customers(
    customer_key int, customer_id int, customer_number varchar(50),
    first_name varchar(50), last_name varchar(50), country varchar(50),
    marital_status varchar(50), gender varchar(50), birthdate date, create_date date
);

CREATE TABLE gold.dim_products(
    product_key int, product_id int, product_number varchar(50),
    product_name varchar(50), category_id varchar(50), category varchar(50),
    subcategory varchar(50), maintenance varchar(50), cost int,
    product_line varchar(50), start_date date
);

CREATE TABLE gold.fact_sales(
    order_number varchar(50), product_key int, customer_key int,
    order_date date, shipping_date date, due_date date,
    sales_amount int, quantity smallint, price int
);
--EXPLORE ALL OBJECTS IN THE DATABASE
SELECT * FROM INFORMATION_SCHEMA.TABLES

--EXPLORE ALL COLUMNS IN THE DATABASE
SELECT * FROM INFORMATION_SCHEMA.COLUMNS

--EXPLORE ALL COUNTRIES OUR CUSTOMER COME FROM
SELECT DISTINCT country FROM gold.dim_customers

--EXPLORE ALL THE CATEGORIES IN PRODUCTS
SELECT DISTINCT category FROM gold.dim_products

--FIND THE DATE OF FIRST AND LAST CUSTOMER
SELECT MIN(order_date) AS first_orderdate
,MAX(order_date) AS last_orderdate,
AGE(MAX(order_date),MIN(order_date)) AS total_timediff
FROM gold.fact_sales

--FIND THE OLEST AND YOUNGEST CUSTOMERS
SELECT MIN(birthdate) AS OLDEST_customer,
 MAX(birthdate) AS YOUNGEST_customer
FROM gold.dim_customers

--FIND THE TOTAL SALES
SELECT SUM(sales_amount) AS TOTAL_SALES FROM gold.fact_sales

--FIND HOW MANY ITEMS ARE SOLD
SELECT SUM(quantity) AS TOTAL_ITEMS FROM gold.fact_sales

--FIND THE AVERAGE SELLING PRICE
SELECT AVG(price) AS AVG_PRICE FROM gold.fact_sales

--FIND THE TOTAL NUMBER OF ORDERS
SELECT COUNT(order_number) AS TOTAL_NUMBER_OF_ORDERS FROM gold.fact_sales

--FIND THE TOTAL NUMBER OF PRODUCTS
SELECT COUNT(product_number) AS TOTAL_NUMBER_OF_PRODUCT FROM gold.dim_products

--FIND THE TOTAL NUMBER OF CUSTOMERS
SELECT COUNT(customer_key) AS total_number_of_customer FROM gold.dim_customers

--FIND THE TOTAL NUMBER OF CUSTOMERS THAT HAS PLACES AN ORDER
SELECT COUNT( DISTINCT customer_key) AS total_number_of_customer FROM gold.dim_customers

--GENARATE A REPORT THAT SHOWS ALL KEY METRICS OF THE BUSINESS
SELECT 'TOTAL_SALES' AS Measure_name ,SUM(sales_amount) AS Measure_Value FROM gold.fact_sales
UNION ALL
SELECT 'TOTAL_QUANTITY' AS Measure_Value,SUM(quantity) AS Measure_Value FROM gold.fact_sales
UNION ALL
SELECT 'AVERAGE_SELLING_PRICE' as Measure_Name, AVG(price) AS Measure_Value  FROM gold.fact_sales
UNION ALL
SELECT 'TOTAL_ORDERS' AS Measure_Name,COUNT(order_number) AS Measure_Value FROM gold.fact_sales
UNION ALL
SELECT 'TOTAL_PRODUCTS' AS Measure_Name,COUNT(product_number) AS Measure_Value FROM gold.dim_products
UNION ALL
SELECT 'TOTAL_CUSTOMERS' AS Measure_Name,COUNT(customer_key) AS Measure_Value FROM gold.dim_customers
UNION ALL
SELECT 'TOTAL_CUSTOMER_BY_ORDERS' AS Measure_Name,COUNT( DISTINCT customer_key) AS Measure_Value FROM gold.dim_customers

--MAGNITUDE ANALYSIS
--FIND THE TOTAL CUSTOMERS BY COUNTRIES
SELECT COUNT(customer_key) AS Total_Customer, country FROM gold.dim_customers
GROUP BY country 
ORDER BY Total_Customer DESC

--FIND TOTAL CUSTOMERS BY GENDER
SELECT COUNT(customer_key) AS Total_Customer, gender FROM gold.dim_customers
GROUP BY gender

--FIND TOTAL PRODUCTS BY CATEGORY
SELECT COUNT(product_key) AS Total_Product, category FROM gold.dim_products
GROUP BY category
ORDER BY Total_Product DESC

--WHAT IS THE AVERAGE COST OF EACH CATEGORY
SELECT AVG(cost) AS AVG_COST, category FROM gold.dim_products
GROUP BY category
ORDER BY AVG_COST DESC

--WHAT IS THE TOTAL REVENUE GENERATED FOR EACH CATEGORY
SELECT SUM(s.sales_amount) AS Total_revenue, p.category FROM gold.fact_sales s
LEFT JOIN gold.dim_products p ON s.product_key = p.product_key
GROUP BY P.category
ORDER BY Total_revenue DESC

--WHAT IS THE TOTAL REVENUE GENERATED BY EACH CUSTOMER
SELECT c.first_name, c.customer_key ,SUM(s.sales_amount) AS Total_revenue_bycustomer FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c ON s.customer_key = c.customer_key
GROUP BY c.customer_key , c.first_name
ORDER BY Total_revenue_bycustomer DESC

--WHAT IS THE DISTRIBUTION OF SOLD ITEMS ACROSS COUNTRIES
SELECT c.country, SUM(s.quantity) AS Total_distribution FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c ON s.customer_key = c.customer_key
GROUP BY c.country
ORDER BY Total_distribution DESC

--RANKING ANALYSIS
--WHICH 5 PRODUCTS GENERATE THE HIGHEST REVENUE
SELECT SUM(s.sales_amount) AS Total_revenue, p.product_name FROM gold.fact_sales s
LEFT JOIN gold.dim_products p ON s.product_key = p.product_key
GROUP BY p.product_name
ORDER BY Total_revenue DESC
LIMIT 5

--WHICH 5 PRODUCTS GENERATE THE WORST REVENUE
SELECT SUM(s.sales_amount) AS Total_revenue, p.product_name FROM gold.fact_sales s
LEFT JOIN gold.dim_products p ON s.product_key = p.product_key
GROUP BY p.product_name
ORDER BY Total_revenue 
LIMIT 5


--ANALYZE SALES PERFORMACE OVER TIME
SELECT SUM(sales_amount) AS TOTAL_SALES , 
COUNT( DISTINCT customer_key) as Total_customers,
EXTRACT(YEAR FROM order_date) AS order_year
FROM gold.fact_sales
GROUP BY  order_year 
ORDER BY order_year

--CUMULATIVE ANALYSIS
--CALCULATE THE TOTAL SALES PER MONTH AND THE RUNNING TOTAL OF SALES OVER TIME
SELECT 
order_Month,
Total_sales,
SUM(Total_sales) OVER (ORDER BY Order_Month) AS running_total_sales
FROM
(SELECT DATE_TRUNC('month', order_date)::date  AS order_Month,
SUM(sales_amount ) AS Total_sales
FROM gold.fact_sales
GROUP BY order_Month) AS monthly_sales
ORDER BY order_Month;

--PERFORMANCE ANALYSIS
--ANALYE THE YEARLY PERFORMANCE OF PRODUCTS BY COMPARING EACH PRODUCT'S SALES TO BOTH 
--ITS AVERAGE SALES PERFORMANCE AND THE PREVIOUS YEAR'S SALES
WITH yearly_product_sales AS
(SELECT 
DATE_TRUNC('year',f.order_date)::date AS order_year,
 p.product_name , 
 SUM(f.sales_amount) AS current_sales
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON f.product_key = p.product_key
GROUP BY order_year,p.product_name)
SELECT 
order_year,
product_name,
current_sales,
AVG(current_sales) OVER(PARTITION BY product_name) AS avg_sales,
current_sales - AVG(current_sales) OVER(PARTITION BY product_name)  AS diff_avg,
CASE WHEN current_sales - AVG(current_sales) OVER(PARTITION BY product_name) > 0 THEN 'above_Avg'
     WHEN current_sales - AVG(current_sales) OVER(PARTITION BY product_name) < 0 THEN 'below_Avg'
	 ELSE 'avg'
	 END avg_change,
 LAG(current_sales) OVER (PARTITION BY product_name ORDER BY order_year) AS py_sales,
    current_sales - LAG(current_sales) OVER (PARTITION BY product_name ORDER BY order_year) AS diff_py,
    CASE 
        WHEN current_sales - LAG(current_sales) OVER (PARTITION BY product_name ORDER BY order_year) > 0 THEN 'Increase'
        WHEN current_sales - LAG(current_sales) OVER (PARTITION BY product_name ORDER BY order_year) < 0 THEN 'Decrease'
        ELSE 'No Change'
    END AS py_change
FROM yearly_product_sales
ORDER BY order_year,product_name

---- Which categories contribute the most to overall sales?
WITH category_sales as
(SELECT 
p.category, SUM(f.sales_amount) AS Total_sales
FROM gold.dim_products p
LEFT JOIN gold.fact_sales f
ON p.product_key = f.product_key
GROUP BY p.category)
SELECT
    category,
    total_sales,
    SUM(total_sales) OVER () AS overall_sales,
    ROUND((CAST(total_sales AS NUMERIC) / SUM(total_sales) OVER ()) * 100, 2) AS percentage_of_total
FROM category_sales
ORDER BY total_sales DESC;

--SEGMENT PRODUCTS INTO COST RANGES AND COUNT HOW MANY PRODUCTS FALL INTO EACH SEGMENT
WITH product_segments AS 
 (SELECT 
product_key,
product_name,
cost,
CASE WHEN cost < 100 THEN 'Below 100'
     WHEN cost BETWEEN 100 AND 500 THEN '100-500'
	 WHEN cost BETWEEN 500 AND 1000 THEN '500-1000'
	 ELSE 'Above 1000'
	 END cost_range
FROM gold.dim_products
)
SELECT cost_range , COUNT(product_key) AS Total_Products
FROM product_segments
GROUP BY cost_range
ORDER BY Total_Products DESC

--Group customers into three segments based on their spending behavior:
--VIP: Customers with at least 12 months of history and spending more than €5,000.
-- Regular: Customers with at least 12 months of history but spending €5,000 or less.
-- New: Customers with a lifespan less than 12 months.
--And find the total number of customers by each group
WITH customer_spending AS
(SELECT
c.customer_key,
SUM(f.sales_amount) AS Total_spending,
MIN(f.order_date) AS First_order,
MAX(f.order_date) AS Last_order,
(EXTRACT(YEAR FROM MAX(order_date)) - EXTRACT(YEAR FROM MIN(order_date))) * 12 
+ (EXTRACT(MONTH FROM MAX(order_date)) - EXTRACT(MONTH FROM MIN(order_date))) AS lifespan
FROM gold.dim_customers c
LEFT JOIN gold.fact_sales f
ON c.customer_key = f.customer_key
GROUP BY c.customer_key)
SELECT customer_segment, COUNT(customer_key) AS Total_customers
FROM 
(SELECT customer_key,
Total_spending,
lifespan,
CASE WHEN lifespan >= 12 AND Total_spending > 5000 THEN 'VIP'
      WHEN lifespan >= 12 AND Total_spending <= 5000 THEN 'REGULAR'
	  ELSE 'NEW'
	  END AS customer_segment
FROM customer_spending) t
GROUP BY customer_segment
ORDER BY Total_customers DESC

--Customer Report
--Purpose:This report consolidates key customer metrics and behaviors
--Highlights:
   -- 1. Gathers essential fields such as names, ages, and transaction details.
	--2. Segments customers into categories (VIP, Regular, New) and age groups.
   --- 3. Aggregates customer-level metrics:
	  -- - total orders
	  -- - total sales
	  -- - total quantity purchased
	  -- - total products
	  -- - lifespan (in months)
 --    4. Calculates valuable KPIs:
	--    - recency (months since last order)
	--  	- average order value
		--- average monthly spend

CREATE VIEW gold.report_customers AS

WITH base_query AS(
/*---------------------------------------------------------------------------
1) Base Query: Retrieves core columns from tables
---------------------------------------------------------------------------*/
SELECT
f.order_number,
f.product_key,
f.order_date,
f.sales_amount,
f.quantity,
c.customer_key,
c.customer_number,
CONCAT(c.first_name, ' ', c.last_name) AS customer_name,
EXTRACT(YEAR FROM AGE(CURRENT_DATE, birthdate)) AS age
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
WHERE order_date IS NOT NULL)

, customer_aggregation AS (
/*---------------------------------------------------------------------------
2) Customer Aggregations: Summarizes key metrics at the customer level
---------------------------------------------------------------------------*/
SELECT 
	customer_key,
	customer_number,
	customer_name,
	age,
	COUNT(DISTINCT order_number) AS total_orders,
	SUM(sales_amount) AS total_sales,
	SUM(quantity) AS total_quantity,
	COUNT(DISTINCT product_key) AS total_products,
	MAX(order_date) AS last_order_date,
	(EXTRACT(YEAR FROM MAX(order_date)) - EXTRACT(YEAR FROM MIN(order_date))) * 12 
+ (EXTRACT(MONTH FROM MAX(order_date)) - EXTRACT(MONTH FROM MIN(order_date))) AS lifespan
FROM base_query
GROUP BY 
	customer_key,
	customer_number,
	customer_name,
	age
)
SELECT
customer_key,
customer_number,
customer_name,
age,
CASE 
	 WHEN age < 20 THEN 'Under 20'
	 WHEN age between 20 and 29 THEN '20-29'
	 WHEN age between 30 and 39 THEN '30-39'
	 WHEN age between 40 and 49 THEN '40-49'
	 ELSE '50 and above'
END AS age_group,
CASE 
    WHEN lifespan >= 12 AND total_sales > 5000 THEN 'VIP'
    WHEN lifespan >= 12 AND total_sales <= 5000 THEN 'Regular'
    ELSE 'New'
END AS customer_segment,
last_order_date,
(EXTRACT(YEAR FROM CURRENT_DATE) - EXTRACT(YEAR FROM last_order_date)) * 12
+ (EXTRACT(MONTH FROM CURRENT_DATE) - EXTRACT(MONTH FROM last_order_date)) AS recency,
total_orders,
total_sales,
total_quantity,
total_products
lifespan,
-- Compuate average order value (AVO)
CASE WHEN total_sales = 0 THEN 0
	 ELSE total_sales / total_orders
END AS avg_order_value,
-- Compuate average monthly spend
CASE WHEN lifespan = 0 THEN total_sales
     ELSE total_sales / lifespan
END AS avg_monthly_spend
FROM customer_aggregation

--Product Report
    -- This report consolidates key product metrics and behaviors.

--Highlights:
--1. Gathers essential fields such as product name, category, subcategory, and cost.
--2. Segments products by revenue to identify High-Performers, Mid-Range, or Low-Performers.
--3. Aggregates product-level metrics:
-- total orders
-- total sales
-- total quantity sold
-- total customers (unique)
-- lifespan (in months)
--4. Calculates valuable KPIs:
-- recency (months since last sale)
-- average order revenue (AOR)
-- average monthly revenue


CREATE VIEW gold.report_products AS

WITH base_query AS (
/*---------------------------------------------------------------------------
1) Base Query: Retrieves core columns from fact_sales and dim_products
---------------------------------------------------------------------------*/
    SELECT
	    f.order_number,
        f.order_date,
		f.customer_key,
        f.sales_amount,
        f.quantity,
        p.product_key,
        p.product_name,
        p.category,
        p.subcategory,
        p.cost
    FROM gold.fact_sales f
    LEFT JOIN gold.dim_products p
        ON f.product_key = p.product_key
    
),

product_aggregations AS (
/*---------------------------------------------------------------------------
2) Product Aggregations: Summarizes key metrics at the product level
---------------------------------------------------------------------------*/
SELECT
    product_key,
    product_name,
    category,
    subcategory,
    cost,
	(EXTRACT(YEAR FROM MAX(order_date)) - EXTRACT(YEAR FROM MIN(order_date))) * 12
+ (EXTRACT(MONTH FROM MAX(order_date)) - EXTRACT(MONTH FROM MIN(order_date))) AS lifespan,
    MAX(order_date) AS last_sale_date,
    COUNT(DISTINCT order_number) AS total_orders,
	COUNT(DISTINCT customer_key) AS total_customers,
    SUM(sales_amount) AS total_sales,
    SUM(quantity) AS total_quantity,
	ROUND(AVG(CAST(sales_amount AS NUMERIC) / NULLIF(quantity, 0)),1) AS avg_selling_price
FROM base_query

GROUP BY
    product_key,
    product_name,
    category,
    subcategory,
    cost
)

/*---------------------------------------------------------------------------
  3) Final Query: Combines all product results into one output
---------------------------------------------------------------------------*/
SELECT 
	product_key,
	product_name,
	category,
	subcategory,
	cost,
	last_sale_date,
	(EXTRACT(YEAR FROM CURRENT_DATE) - EXTRACT(YEAR FROM last_sale_date)) * 12
+ (EXTRACT(MONTH FROM CURRENT_DATE) - EXTRACT(MONTH FROM last_sale_date)) AS recency_in_months,
	CASE
		WHEN total_sales > 50000 THEN 'High-Performer'
		WHEN total_sales >= 10000 THEN 'Mid-Range'
		ELSE 'Low-Performer'
	END AS product_segment,
	lifespan,
	total_orders,
	total_sales,
	total_quantity,
	total_customers,
	avg_selling_price,
	-- Average Order Revenue (AOR)
	CASE 
		WHEN total_orders = 0 THEN 0
		ELSE total_sales / total_orders
	END AS avg_order_revenue,

	-- Average Monthly Revenue
	CASE
		WHEN lifespan = 0 THEN total_sales
		ELSE total_sales / lifespan
	END AS avg_monthly_revenue

FROM product_aggregations 





 











